/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pom.java;

import java.util.Scanner;

import static pom.java.CleanString.lowerCase;
import static pom.java.CleanString.removeSpecialCharsAndSpace;

public class App {

    public static String commandInsert() {
        Scanner scanner = new Scanner(System.in);
        return scanner.nextLine();
    }

    public static boolean palindrome(String text) {
        String lowerCase = lowerCase(text);
        String reversedString = new ReverseString(lowerCase).reversedString();
        String reversedAndRemovedSpecialChars = removeSpecialCharsAndSpace(reversedString);

        String originalRemovedSpecialChars = removeSpecialCharsAndSpace(lowerCase);
        return reversedAndRemovedSpecialChars.equals(originalRemovedSpecialChars);
    }

    public static void main(String[] args) {
        String textInserted = commandInsert();
        System.out.println(palindrome(textInserted));
    }
}
